/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.rufus.sambagui;

/**
 *
 * @author root
 */
public class AnadirValor extends javax.swing.JDialog {

    String[] opcionValor = new String[2];
    
    
    
    
    /**
     * Creates new form anadirValor
     */
    public AnadirValor(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        panelPrincipal.setVisible(true);
        panelMask.setVisible(false);
        panelDirMask.setVisible(false);
        panelGuest.setVisible(false);
        panelRead.setVisible(false);
    }

    
    public String[] getDatos(){
        this.setVisible(true);
        return opcionValor;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboOpcion = new javax.swing.JComboBox<>();
        botonAtras1 = new javax.swing.JButton();
        panelRead = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoRead = new javax.swing.JTextField();
        botonAtras4 = new javax.swing.JButton();
        botonOk4 = new javax.swing.JButton();
        panelMask = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonAtras2 = new javax.swing.JButton();
        botonOk2 = new javax.swing.JButton();
        campoMask = new javax.swing.JTextField();
        panelDirMask = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        campoDirMask = new javax.swing.JTextField();
        botonAtras3 = new javax.swing.JButton();
        botonOk3 = new javax.swing.JButton();
        panelGuest = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        campoGuest = new javax.swing.JTextField();
        botonAtras5 = new javax.swing.JButton();
        botonOk5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(45, 45, 45));

        jLabel2.setText("Selecciona Opción");

        comboOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Create mask", "Create directory mask", "guest ok", "read only" }));
        comboOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOpcionActionPerformed(evt);
            }
        });

        botonAtras1.setText("Atrás");
        botonAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtras1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(comboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(botonAtras1)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAtras1)
                .addGap(18, 18, 18))
        );

        jLabel4.setText("Read Only:");

        campoRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoReadActionPerformed(evt);
            }
        });

        botonAtras4.setText("Cancelar");
        botonAtras4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtras4ActionPerformed(evt);
            }
        });

        botonOk4.setText("Ok");
        botonOk4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOk4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReadLayout = new javax.swing.GroupLayout(panelRead);
        panelRead.setLayout(panelReadLayout);
        panelReadLayout.setHorizontalGroup(
            panelReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReadLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoRead, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(panelReadLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(botonAtras4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonOk4)
                .addGap(24, 24, 24))
        );
        panelReadLayout.setVerticalGroup(
            panelReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReadLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(panelReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoRead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(panelReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAtras4)
                    .addComponent(botonOk4))
                .addGap(20, 20, 20))
        );

        jLabel1.setText("Create Mask");

        botonAtras2.setText("Cancelar");
        botonAtras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtras2ActionPerformed(evt);
            }
        });

        botonOk2.setText("Ok");
        botonOk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOk2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMaskLayout = new javax.swing.GroupLayout(panelMask);
        panelMask.setLayout(panelMaskLayout);
        panelMaskLayout.setHorizontalGroup(
            panelMaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaskLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(botonAtras2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(botonOk2)
                .addGap(26, 26, 26))
            .addGroup(panelMaskLayout.createSequentialGroup()
                .addGroup(panelMaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMaskLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(panelMaskLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(campoMask, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMaskLayout.setVerticalGroup(
            panelMaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaskLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonOk2)
                    .addComponent(botonAtras2))
                .addGap(14, 14, 14))
        );

        jLabel3.setText("Directory mask");

        botonAtras3.setText("Cancelar");
        botonAtras3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtras3ActionPerformed(evt);
            }
        });

        botonOk3.setText("Ok");
        botonOk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOk3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDirMaskLayout = new javax.swing.GroupLayout(panelDirMask);
        panelDirMask.setLayout(panelDirMaskLayout);
        panelDirMaskLayout.setHorizontalGroup(
            panelDirMaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDirMaskLayout.createSequentialGroup()
                .addGroup(panelDirMaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDirMaskLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel3))
                    .addGroup(panelDirMaskLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(campoDirMask, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDirMaskLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(botonAtras3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonOk3)
                .addGap(48, 48, 48))
        );
        panelDirMaskLayout.setVerticalGroup(
            panelDirMaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDirMaskLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoDirMask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(panelDirMaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAtras3)
                    .addComponent(botonOk3))
                .addGap(21, 21, 21))
        );

        jLabel5.setText("Guest ok:");

        botonAtras5.setText("Cancelar");
        botonAtras5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtras5ActionPerformed(evt);
            }
        });

        botonOk5.setText("Ok");
        botonOk5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOk5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGuestLayout = new javax.swing.GroupLayout(panelGuest);
        panelGuest.setLayout(panelGuestLayout);
        panelGuestLayout.setHorizontalGroup(
            panelGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuestLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGuestLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(campoGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(panelGuestLayout.createSequentialGroup()
                        .addComponent(botonAtras5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonOk5)
                        .addGap(27, 27, 27))))
        );
        panelGuestLayout.setVerticalGroup(
            panelGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuestLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(panelGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoGuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(panelGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAtras5)
                    .addComponent(botonOk5))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMask, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDirMask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDirMask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelGuest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOpcionActionPerformed
        String eleccion = comboOpcion.getSelectedItem().toString();
        if(eleccion.equals("Create mask")){
            panelPrincipal.setVisible(false);
            panelMask.setVisible(true);
        }else if(eleccion.equals("Create directory mask")){
            panelPrincipal.setVisible(false);
            panelDirMask.setVisible(true);
        }else if(eleccion.equals("read only")){
            panelPrincipal.setVisible(false);
            panelRead.setVisible(true);
        }else{
            panelPrincipal.setVisible(false);
            panelGuest.setVisible(true);
        }
        opcionValor[0] = eleccion;
    }//GEN-LAST:event_comboOpcionActionPerformed

    private void botonAtras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtras2ActionPerformed
        opcionValor = null;
        dispose();
    }//GEN-LAST:event_botonAtras2ActionPerformed

    private void botonOk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOk2ActionPerformed
        if(campoMask.getText().equals("")){
            opcionValor = null;
        }else{
            opcionValor[1] = campoMask.getText();
            
        }
        dispose();
    }//GEN-LAST:event_botonOk2ActionPerformed

    private void botonAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtras1ActionPerformed
        opcionValor = null;
        dispose();
    }//GEN-LAST:event_botonAtras1ActionPerformed

    private void botonAtras3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtras3ActionPerformed
        opcionValor = null;
        dispose();
    }//GEN-LAST:event_botonAtras3ActionPerformed

    private void botonOk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOk3ActionPerformed
        if(campoDirMask.getText().equals("")){
            opcionValor = null;
        }else{
            opcionValor[1] = campoDirMask.getText();
            
        }
        dispose();
    }//GEN-LAST:event_botonOk3ActionPerformed

    private void botonAtras4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtras4ActionPerformed
        opcionValor = null;
        dispose();
    }//GEN-LAST:event_botonAtras4ActionPerformed

    private void botonOk4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOk4ActionPerformed
        if(campoRead.getText().equals("")){
            opcionValor = null;
        }else{
            opcionValor[1] = campoRead.getText();
            
        }
        dispose();
    }//GEN-LAST:event_botonOk4ActionPerformed

    private void campoReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoReadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoReadActionPerformed

    private void botonAtras5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtras5ActionPerformed
        opcionValor = null;
        dispose();
    }//GEN-LAST:event_botonAtras5ActionPerformed

    private void botonOk5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOk5ActionPerformed
        if(campoGuest.getText().equals("")){
            opcionValor = null;
        }else{
            opcionValor[1] = campoGuest.getText();
            
        }
        dispose();
    }//GEN-LAST:event_botonOk5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnadirValor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnadirValor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnadirValor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnadirValor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AnadirValor dialog = new AnadirValor(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras1;
    private javax.swing.JButton botonAtras2;
    private javax.swing.JButton botonAtras3;
    private javax.swing.JButton botonAtras4;
    private javax.swing.JButton botonAtras5;
    private javax.swing.JButton botonOk2;
    private javax.swing.JButton botonOk3;
    private javax.swing.JButton botonOk4;
    private javax.swing.JButton botonOk5;
    private javax.swing.JTextField campoDirMask;
    private javax.swing.JTextField campoGuest;
    private javax.swing.JTextField campoMask;
    private javax.swing.JTextField campoRead;
    private javax.swing.JComboBox<String> comboOpcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelDirMask;
    private javax.swing.JPanel panelGuest;
    private javax.swing.JPanel panelMask;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRead;
    // End of variables declaration//GEN-END:variables
}
