/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.rufus.sambagui;

import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class EditarSeccion extends javax.swing.JDialog {

    private Compartir compartir;
    private boolean confirmarCambios;
    private String seccionEditandose;
    
    /**
     * Creates new form Editar
     */
    public EditarSeccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
    }

    public void inicializar(Compartir compartir, String seccionAEditar){
        this.compartir = compartir;
        seccionEditandose = seccionAEditar;
        iniciarTabla(seccionEditandose);
    }
    
    private void iniciarTabla(String nombreSeccion){
        nombreRecurso.setText("Recurso " + nombreSeccion);  
        //Compartir me dará los valores de la seccion
        Map<String,String> parValores = compartir.getValoresSeccion(nombreSeccion);
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaOpcion.getModel();
        
        //Lleno la tabla con esos valores
        if (parValores != null) {
            // Iterar sobre todas las claves y valores en la sección
            for (Map.Entry<String, String> entry : parValores.entrySet()) {
                modeloTabla.addRow(new String[]{entry.getKey(),entry.getValue()});
            }
        }else{
            System.out.println("La sección especificada no existe. (CLASE EDITARSECCION,iniciarTabla())");
        }
    }
    
    public boolean taMadreEstoyCansado(){
        return confirmarCambios;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreRecurso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOpcion = new javax.swing.JTable();
        botonAddValor = new javax.swing.JButton();
        botonEditValor = new javax.swing.JButton();
        botonDeleteValor = new javax.swing.JButton();
        botonBack = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));

        nombreRecurso.setForeground(new java.awt.Color(242, 242, 242));
        nombreRecurso.setText("Recurso");

        tablaOpcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Opción", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaOpcion.setCellSelectionEnabled(false);
        tablaOpcion.setRowSelectionAllowed(true);
        tablaOpcion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaOpcion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaOpcion.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaOpcion);
        tablaOpcion.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        botonAddValor.setText("Añadir");
        botonAddValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddValorActionPerformed(evt);
            }
        });

        botonEditValor.setText("Editar");
        botonEditValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditValorActionPerformed(evt);
            }
        });

        botonDeleteValor.setText("Eliminar");
        botonDeleteValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeleteValorActionPerformed(evt);
            }
        });

        botonBack.setText("Atrás");
        botonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBackActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonAddValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonEditValor)
                                .addGap(70, 70, 70)
                                .addComponent(botonDeleteValor))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(botonBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonGuardar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(nombreRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(nombreRecurso)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAddValor)
                    .addComponent(botonEditValor)
                    .addComponent(botonDeleteValor))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBack)
                    .addComponent(botonGuardar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAddValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddValorActionPerformed
        AnadirValor formulario = new AnadirValor(this, true);
        formulario.setVisible(true);
    }//GEN-LAST:event_botonAddValorActionPerformed

    private void botonEditValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditValorActionPerformed
        if(tablaOpcion.getSelectedRow() != -1){
            String editandoOpcion = (String) tablaOpcion.getValueAt(tablaOpcion.getSelectedRow(), 0);
            System.out.println("Editando la Opcion : " + editandoOpcion);
        }
    }//GEN-LAST:event_botonEditValorActionPerformed

    private void botonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBackActionPerformed
        confirmarCambios = false;
        dispose();
    }//GEN-LAST:event_botonBackActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        confirmarCambios = true;
        dispose();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonDeleteValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeleteValorActionPerformed
        if(tablaOpcion.getSelectedRow() != -1){
            String editandoOpcion = (String) tablaOpcion.getValueAt(tablaOpcion.getSelectedRow(), 0);
            compartir.deleteValor(seccionEditandose, editandoOpcion);
        }
    }//GEN-LAST:event_botonDeleteValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarSeccion dialog = new EditarSeccion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAddValor;
    private javax.swing.JButton botonBack;
    private javax.swing.JButton botonDeleteValor;
    private javax.swing.JButton botonEditValor;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreRecurso;
    private javax.swing.JTable tablaOpcion;
    // End of variables declaration//GEN-END:variables
}
