/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.rufus.sambagui;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author julio
 */
public class shareFormAdd extends javax.swing.JDialog {

    /**
     * Creates new form shareFormAdd
     */
    public shareFormAdd(java.awt.Frame parent, boolean modal) {
        super(parent, "Agregar recurso compartido", modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shareAddForm = new javax.swing.JPanel();
        shareLabel = new javax.swing.JLabel();
        shareText = new javax.swing.JTextField();
        pathLabel = new javax.swing.JLabel();
        pathText = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        permissionsLabel = new javax.swing.JLabel();
        accessPermissions = new javax.swing.JLayeredPane();
        ownerLabel = new javax.swing.JLabel();
        groupsLabel = new javax.swing.JLabel();
        othersLabel = new javax.swing.JLabel();
        readLabel = new javax.swing.JLabel();
        writeLabel = new javax.swing.JLabel();
        executeLabel = new javax.swing.JLabel();
        readOwner = new javax.swing.JRadioButton();
        writeOwner = new javax.swing.JRadioButton();
        executeOwner = new javax.swing.JRadioButton();
        readGroups = new javax.swing.JRadioButton();
        writeGroups = new javax.swing.JRadioButton();
        executeGroups = new javax.swing.JRadioButton();
        readOthers = new javax.swing.JRadioButton();
        writeOthers = new javax.swing.JRadioButton();
        executeOthers = new javax.swing.JRadioButton();
        commentLabel = new javax.swing.JLabel();
        commentText = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        ownerUserLabel = new javax.swing.JLabel();
        userList = new javax.swing.JComboBox<>();
        ownerGroupsLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        ownershipLabel = new javax.swing.JLabel();
        saveFormButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(575, 500));

        shareAddForm.setBackground(new java.awt.Color(30, 30, 30));
        shareAddForm.setPreferredSize(new java.awt.Dimension(575, 500));

        shareLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        shareLabel.setForeground(new java.awt.Color(255, 255, 255));
        shareLabel.setText("Share name");

        shareText.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        shareText.setForeground(new java.awt.Color(255, 255, 255));

        pathLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        pathLabel.setForeground(new java.awt.Color(255, 255, 255));
        pathLabel.setText("Path");

        pathText.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        pathText.setForeground(new java.awt.Color(255, 255, 255));

        findButton.setBackground(new java.awt.Color(62, 62, 62));
        findButton.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        findButton.setForeground(new java.awt.Color(255, 255, 255));
        findButton.setText("Buscar");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        permissionsLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        permissionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        permissionsLabel.setText("Access Permissions");

        accessPermissions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        accessPermissions.setForeground(new java.awt.Color(255, 255, 255));

        ownerLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ownerLabel.setForeground(new java.awt.Color(255, 255, 255));
        ownerLabel.setText("Owner");

        groupsLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        groupsLabel.setForeground(new java.awt.Color(255, 255, 255));
        groupsLabel.setText("Groups");

        othersLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        othersLabel.setForeground(new java.awt.Color(255, 255, 255));
        othersLabel.setText("Others");

        readLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        readLabel.setForeground(new java.awt.Color(255, 255, 255));
        readLabel.setText("r");

        writeLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        writeLabel.setForeground(new java.awt.Color(255, 255, 255));
        writeLabel.setText("w");

        executeLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        executeLabel.setForeground(new java.awt.Color(255, 255, 255));
        executeLabel.setText("x");

        accessPermissions.setLayer(ownerLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(groupsLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(othersLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(readLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(writeLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(executeLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(readOwner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(writeOwner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(executeOwner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(readGroups, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(writeGroups, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(executeGroups, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(readOthers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(writeOthers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        accessPermissions.setLayer(executeOthers, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout accessPermissionsLayout = new javax.swing.GroupLayout(accessPermissions);
        accessPermissions.setLayout(accessPermissionsLayout);
        accessPermissionsLayout.setHorizontalGroup(
            accessPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accessPermissionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accessPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accessPermissionsLayout.createSequentialGroup()
                        .addComponent(othersLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(readOthers))
                    .addGroup(accessPermissionsLayout.createSequentialGroup()
                        .addComponent(ownerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(accessPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(readLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(readOwner, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(accessPermissionsLayout.createSequentialGroup()
                        .addComponent(groupsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(readGroups)))
                .addGap(36, 36, 36)
                .addGroup(accessPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(writeLabel)
                    .addComponent(writeOwner)
                    .addComponent(writeGroups)
                    .addComponent(writeOthers))
                .addGap(30, 30, 30)
                .addGroup(accessPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(executeLabel)
                    .addComponent(executeOwner)
                    .addComponent(executeGroups)
                    .addComponent(executeOthers))
                .addGap(34, 34, 34))
        );
        accessPermissionsLayout.setVerticalGroup(
            accessPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accessPermissionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accessPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readLabel)
                    .addComponent(writeLabel)
                    .addComponent(executeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(accessPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accessPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ownerLabel)
                        .addComponent(readOwner))
                    .addComponent(writeOwner)
                    .addComponent(executeOwner))
                .addGap(18, 18, 18)
                .addGroup(accessPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(executeGroups)
                    .addComponent(writeGroups)
                    .addComponent(groupsLabel)
                    .addComponent(readGroups))
                .addGap(18, 18, 18)
                .addGroup(accessPermissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(othersLabel)
                    .addComponent(readOthers)
                    .addComponent(writeOthers)
                    .addComponent(executeOthers))
                .addGap(172, 172, 172))
        );

        commentLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        commentLabel.setForeground(new java.awt.Color(255, 255, 255));
        commentLabel.setText("Comment");

        commentText.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        commentText.setForeground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLayeredPane1.setForeground(new java.awt.Color(255, 255, 255));

        ownerUserLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ownerUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        ownerUserLabel.setText("User");

        userList.setBackground(new java.awt.Color(62, 62, 62));
        userList.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        userList.setForeground(new java.awt.Color(255, 255, 255));
        userList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "julio", "aso10" }));

        ownerGroupsLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ownerGroupsLabel.setForeground(new java.awt.Color(255, 255, 255));
        ownerGroupsLabel.setText("Groups");

        jComboBox1.setBackground(new java.awt.Color(62, 62, 62));
        jComboBox1.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "users", "aso01" }));

        jLayeredPane1.setLayer(ownerUserLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(userList, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ownerGroupsLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ownerUserLabel)
                    .addComponent(userList, 0, 200, Short.MAX_VALUE)
                    .addComponent(ownerGroupsLabel)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ownerUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ownerGroupsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        ownershipLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ownershipLabel.setForeground(new java.awt.Color(255, 255, 255));
        ownershipLabel.setText("Ownership");

        saveFormButton.setBackground(new java.awt.Color(62, 62, 62));
        saveFormButton.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        saveFormButton.setForeground(new java.awt.Color(255, 255, 255));
        saveFormButton.setText("Guardar");

        cancelButton.setBackground(new java.awt.Color(62, 62, 62));
        cancelButton.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shareAddFormLayout = new javax.swing.GroupLayout(shareAddForm);
        shareAddForm.setLayout(shareAddFormLayout);
        shareAddFormLayout.setHorizontalGroup(
            shareAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shareAddFormLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(shareAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shareAddFormLayout.createSequentialGroup()
                        .addComponent(commentLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(shareAddFormLayout.createSequentialGroup()
                        .addGroup(shareAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shareText)
                            .addComponent(commentText)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shareAddFormLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(shareAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shareAddFormLayout.createSequentialGroup()
                                        .addComponent(cancelButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(saveFormButton))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shareAddFormLayout.createSequentialGroup()
                                        .addComponent(permissionsLabel)
                                        .addGap(136, 136, 136)
                                        .addGroup(shareAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ownershipLabel)
                                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(shareAddFormLayout.createSequentialGroup()
                                .addGroup(shareAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pathLabel)
                                    .addComponent(shareLabel)
                                    .addGroup(shareAddFormLayout.createSequentialGroup()
                                        .addComponent(pathText, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(findButton))
                                    .addComponent(accessPermissions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(56, 56, 56))))
        );
        shareAddFormLayout.setVerticalGroup(
            shareAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shareAddFormLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(shareLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shareText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shareAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findButton))
                .addGap(18, 18, 18)
                .addGroup(shareAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permissionsLabel)
                    .addComponent(ownershipLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shareAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accessPermissions, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(commentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(shareAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveFormButton)
                    .addComponent(cancelButton))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shareAddForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shareAddForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        int result = javax.swing.JOptionPane.showConfirmDialog(
                null,
                "¿Estás seguro que deseas cancelar?\nToda la información que se haya agregado no se guardará.",
                "Confirmación",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (result == javax.swing.JOptionPane.YES_OPTION) {
            // Si se presiona "Aceptar", cerrar la ventana
            dispose();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            // Aquí puedes trabajar con el archivo seleccionado
        }
    }//GEN-LAST:event_findButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shareFormAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shareFormAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shareFormAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shareFormAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                shareFormAdd dialog = new shareFormAdd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane accessPermissions;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JTextField commentText;
    private javax.swing.JRadioButton executeGroups;
    private javax.swing.JLabel executeLabel;
    private javax.swing.JRadioButton executeOthers;
    private javax.swing.JRadioButton executeOwner;
    private javax.swing.JButton findButton;
    private javax.swing.JLabel groupsLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel othersLabel;
    private javax.swing.JLabel ownerGroupsLabel;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JLabel ownerUserLabel;
    private javax.swing.JLabel ownershipLabel;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextField pathText;
    private javax.swing.JLabel permissionsLabel;
    private javax.swing.JRadioButton readGroups;
    private javax.swing.JLabel readLabel;
    private javax.swing.JRadioButton readOthers;
    private javax.swing.JRadioButton readOwner;
    private javax.swing.JButton saveFormButton;
    private javax.swing.JPanel shareAddForm;
    private javax.swing.JLabel shareLabel;
    private javax.swing.JTextField shareText;
    private javax.swing.JComboBox<String> userList;
    private javax.swing.JRadioButton writeGroups;
    private javax.swing.JLabel writeLabel;
    private javax.swing.JRadioButton writeOthers;
    private javax.swing.JRadioButton writeOwner;
    // End of variables declaration//GEN-END:variables
}
