/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.rufus.sambagui;

/**
 *
 * @author julio
 */
public class userFormAdd extends javax.swing.JDialog {

    /**
     * Creates new form userForm
     */
    public userFormAdd(java.awt.Frame parent, boolean modal) {
        super(parent, "Agregar Usuario", modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUserForm = new javax.swing.JPanel();
        usernameText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        passwdText = new javax.swing.JPasswordField();
        cancelFormButton = new javax.swing.JButton();
        saveFormButton = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        passwdLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addUserForm.setBackground(new java.awt.Color(30, 30, 30));

        usernameText.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        nameText.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        passwdText.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N

        cancelFormButton.setBackground(new java.awt.Color(62, 62, 62));
        cancelFormButton.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        cancelFormButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelFormButton.setText("Cancelar");
        cancelFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFormButtonActionPerformed(evt);
            }
        });

        saveFormButton.setBackground(new java.awt.Color(62, 62, 62));
        saveFormButton.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        saveFormButton.setForeground(new java.awt.Color(255, 255, 255));
        saveFormButton.setText("Guardar");

        userLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("Username");

        nameLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");

        passwdLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        passwdLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwdLabel.setText("Password");

        javax.swing.GroupLayout addUserFormLayout = new javax.swing.GroupLayout(addUserForm);
        addUserForm.setLayout(addUserFormLayout);
        addUserFormLayout.setHorizontalGroup(
            addUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserFormLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(addUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwdLabel)
                    .addComponent(nameLabel)
                    .addComponent(userLabel)
                    .addGroup(addUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(addUserFormLayout.createSequentialGroup()
                            .addComponent(cancelFormButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                            .addComponent(saveFormButton))
                        .addComponent(usernameText)
                        .addComponent(nameText)
                        .addComponent(passwdText)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        addUserFormLayout.setVerticalGroup(
            addUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addUserFormLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(userLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelFormButton)
                    .addComponent(saveFormButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addUserForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addUserForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFormButtonActionPerformed
        int result = javax.swing.JOptionPane.showConfirmDialog(
            null,
            "¿Estás seguro que deseas cancelar?\nToda la información que se haya agregado no se guardará.",
            "Confirmación",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (result == javax.swing.JOptionPane.YES_OPTION) {
            // Si se presiona "Aceptar", cerrar la ventana
            dispose();
        }
    }//GEN-LAST:event_cancelFormButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userFormAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userFormAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userFormAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userFormAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                userFormAdd dialog = new userFormAdd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addUserForm;
    private javax.swing.JButton cancelFormButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel passwdLabel;
    private javax.swing.JPasswordField passwdText;
    private javax.swing.JButton saveFormButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
